[pytest]
# Agrega la carpeta actual al PYTHONPATH para que pytest pueda encontrar los módulos de la aplicación
pythonpath = .

# Carpeta donde pytest buscará los tests
testpaths = tests

# Prefijo o patrón de archivos que pytest ejecutará
# pytest ejecutará archivos que comiencen con test_ o terminen con _tests.py
python_files = test_*.py *_tests.py

# Opciones adicionales para pytest
# -v muestra cada prueba ejecutada
# -ra # Reporta resumen de tests PASADOS (P), SKIPPED (s), FAILED (F)
# -rA # Reporta resumen de todos los tests
# --cov=app # Habilita la cobertura de código para la carpeta 'app'
# --cov-report=html # Genera un reporte HTML con la cobertura

addopts = 
        -v -ra -rA --capture=sys
        --cov=app
        --cov-report=term-missing
        --cov-report=html
# Ignorar warnings
# ignore::UserWarning ignora warnings de tipo UserWarning
# ignore::DeprecationWarning: ignora solo los warnings de deprecación
filterwarnings = 
                ignore::UserWarning 
                ignore::DeprecationWarning

